# Starter pipeline

trigger:
- main

pool:
  name: Default

jobs:
- job: BuildFrontendDockerImage
  displayName: 'Build Frontend Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Build Frontend Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/angular/Dockerfile'
      tags: |
        $(Build.BuildId)
