trigger:
- main

pool:
  name: Default

jobs: 
- job: SecurityScan
  displayName: 'Security Scan Docker Image'
  steps:
  - task: trivy@1
    inputs:
      version: 'latest'
      imageName: 'hadil0505/palestia:palestiaBackend'
      severities: 'CRITICAL,HIGH'
