trigger:
- main

pool:
  name: Default

jobs:
- job: SecurityScan
  displayName: 'Scan container image for vulnerabilities'
  steps:
  - task: trivy@1
    displayName: 'Run Trivy Security Scan'
    inputs:
      image: 'hadil0505/palestia:palestiaBackend'
      exitCode: $(trivyExitCode)
      docker: false
      version: 'latest'

