trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: SecurityScan
  displayName: 'Scan container image for vulnerabilities'
  steps:
  - task: CmdLine@2
    inputs:
      script: 'trivy image --format table -o trivy -image-report.html hadil0505/palestia:palestiaBackend'