# Starter pipeline

trigger:
- main

pool:
  name: Default

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Install Node.js'

# Check Node.js and npm versions
- script: |
    node --version
    npm --version
  displayName: 'Verify Node.js and npm versions'