trigger:
- main

pool:
  name: Default

jobs:
- job: PushDockerImage
  displayName: 'Push Docker Image to Docker Hub'
  steps:
  - task: Docker@2
    displayName: 'Push Docker Image to Docker Hub'
    inputs:
      containerRegistry: 'dockerHub_connection'
      repository: 'hadil0505/palestia'
      Dockerfile: 'nest_palestia/Dockerfile'
      command: 'push'
      tags: '$(Build.BuildId)'
