trigger:
- main

pool:
  name: Default

jobs:
- job: dockerPush
  displayName: 'dockerpush'
  steps:
  # Login to Docker Hub
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: 'dockerHub_connection'

  # Build the Docker image
  - task: Docker@2
    inputs:
      command: 'build'
      repository: 'hadil0505/palestia'
      Dockerfile: 'nest_palestia/Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  # Push the Docker image to Docker Hub
  - task: Docker@2
    inputs:
      command: 'push'
      repository: 'hadil0505/palestia'
      tags: |
        $(Build.BuildId)
        latest
