trigger:
- main

pool:
  name: Default

jobs:
- job: SecurityScan
  displayName: 'Security Scan Docker Image'
  steps:
  - task: trivy@1
    inputs:
      version: 'latest'
      path: 'hadil0505/palestia:palestiaBackend'  # Specify the full repository and image tag
      loginDockerConfig: true  # Login to Docker registry if needed
      severities: 'HIGH'  # Set severity level for vulnerabilities
