trigger:
- main

pool:
  name: Default

jobs:
- job: SecurityScan
  displayName: 'Scan container image for vulnerabilities'
  steps:
  - task: trivy@1
    displayName: 'Run Trivy Security Scan'
    inputs:
      image: 'hadil0505/palestia:palestiaBackend'
      exitCode: $(trivyExitCode)
      docker: false
      version: 'latest'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'trivy-results'
      targetPath: '/tmp/trivy-results-0.9395298357853183.json'
