trigger:
- main

pool:
  name: Default

variables:
  frontendImageNameTag: 'palestiaFrontend'
  dockerHubRepository: 'hadil0505/palestia'

stages:
- stage: BuildDockerImages
  displayName: 'Build Docker Images'
  jobs:
  - job: BuildDockerImages
    displayName: 'Build Frontend Docker Image'
    steps:
    - task: Docker@2
      displayName: 'Build Frontend Docker Image'
      inputs:
        containerRegistry: 'dockerHub_connection'
        repository: '$(dockerHubRepository)'
        Dockerfile: 'angular/Dockerfile'
        command: 'build'
        tags: |
          $(Build.BuildId)
          $(frontendImageNameTag)

- stage: PushDockerImages
  displayName: 'Push Docker Images'
  jobs:
  - job: PushDockerImages
    displayName: 'Push Frontend Docker Image to Docker Hub'
    steps:
    - task: Docker@2
      displayName: 'Push Frontend Docker Image to Docker Hub'
      inputs:
        containerRegistry: 'dockerHub_connection'
        repository: '$(dockerHubRepository)'
        command: 'push'
        tags: |
          $(Build.BuildId)
          $(frontendImageNameTag)
