# Starter pipeline

trigger:
- main

pool:
  name: Default

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y git
  displayName: 'Install Git'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self
  fetchDepth: 0

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    cd angular
    npm install --force
    ng build --prod
  displayName: 'npm install and build'