trigger:
- main

pool:
  name: Default

variables:
  imageNameTag: 'palestiaFrontend'  # Define the name tag for the image here

jobs:
- job: BuildAndPushDockerImage
  displayName: 'Build and Push Docker Image to Docker Hub'
  steps:
  - task: Docker@2
    displayName: 'Build Docker Image'
    inputs:
      containerRegistry: 'dockerHub_connection'
      repository: 'hadil0505/palestia'
      Dockerfile: 'angular/Dockerfile'
      command: 'build'
      tags: |
        $(Build.BuildId)
        $(imageNameTag)

  - task: Docker@2
    displayName: 'Push Docker Image to Docker Hub'
    inputs:
      containerRegistry: 'dockerHub_connection'
      repository: 'hadil0505/palestia'
      command: 'push'
      tags: |
        $(Build.BuildId)
        $(imageNameTag)

