# Starter pipeline

trigger:
- main

pool:
  name: Default

jobs:
- job: BuildbackendDockerImage
  displayName: 'Build backend Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Build backend Docker Image'
    inputs:
      command: 'build'
      Dockerfile: '$(Build.SourcesDirectory)/nest_palestia/Dockerfile'
      tags: |
        $(Build.BuildId)
