# Starter pipeline

trigger:
- main

pool:
  name: Default

jobs:
- job: owaspcheck
  displayName: 'owasp check'
  steps:
    - task: dependency-check-build-task@6
      inputs:
        projectName: 'PalestiaToday'
        scanPath: '.'
        format: 'HTML'
        uploadReports: true
