# Starter pipeline

trigger:
- main

pool:
  name: Default

jobs:
- job: owaspcheck
  displayName: 'owasp check'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerHub_connection'
      repository: 'palestia'
      command: 'buildAndPush'
      Dockerfile: 'nest_palestia/Dockerfile'
  