trigger:
- main

pool:
  name: Default

jobs:
- job: SecurityScan
  displayName: 'Scan container image for vulnerabilities'
  steps:
  - task: trivy@1
    displayName: 'Run Trivy Security Scan'
    inputs:
      image: 'hadil0505/palestia:palestiaBackend'
      exitCode: 0
      docker: false
      version: 'latest'

  - script: |
      ls -l /tmp/
    displayName: 'List contents of /tmp directory'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: 'trivy-results'
      targetPath: '/tmp/trivy-results-0.3061783213236191.json'
